# Generated by Django 3.1 on 2020-08-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200826_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
