version: "3"

services: 
    django_stocks:
        build: .
        ports:
            - "8000:8000"
        volumes: 
            - .:/django_stocks
        command: python manage.py runserver 0.0.0.0:8000